### ISSUE TITLE
Error : JsonWebTokenError

### ISSUE THREAD

**Issue by arun-nextbrain** [ansonbenny/Music-Platform#1]
Hi @ansonbenny 
I'm new to this project basically i'm a python developer I wanted to learn react and node
Error : JsonWebTokenError
I don't know why this error is coming 
please help me

**Comment by ansonbenny** [comment]
share the full error message to identify problem.
you must fill .env file

**Comment by arun-nextbrain** [comment]
@ansonbenny 

**.env**
PORT = 5000

MONGO_URL = "mongodb://localhost:27017"

SITE_URL = ""

JWT_SECRET = "xahui8766sns"

SPOTIFY_ID = "33d0b3ec86af4210a781d00e66bf232a"

SPOTIFY_SECRET = "22626f800f4f4a3f94ff4d56d364234a"

MAIL_EMAIL = "designartist.2004@gmail.com"

MAIL_SECRET = "sgbzgtqhmgmbcfeo"

VITE_GOOGLE_CLIENT = "289153080841-7v6rvdgkfa8r66ju27dar2utd5deh09a.apps.googleusercontent.com"

**Client-side console log:**
![Screenshot from 2023-09-22 14-55-41](https://github.com/ansonbenny/Music-Streamer/assets/130034273/aa3d50c3-a2a8-44ce-920e-dff4a0c8db04)
**Server-side console log:**
![Screenshot from 2023-09-22 14-55-38](https://github.com/ansonbenny/Music-Streamer/assets/130034273/b0d7d385-5043-47ea-953d-e0087302f76b)

let know what i'm doing wrong

**Comment by arun-nextbrain** [comment]
> share the full error message to identify problem. you must fill .env file

@ansonbenny 

**.env**
PORT = 5000

MONGO_URL = "mongodb://localhost:27017"

SITE_URL = ""

JWT_SECRET = "xahui8766snjkls"

SPOTIFY_ID = "33d0b3ec86af4210a781d00e66bf232akil"

SPOTIFY_SECRET = "22626f800f4f4a3f94ff4d56d364234aju"

MAIL_EMAIL = "[designartis@gmail.com](mailto:designarti@gmail.com)"

MAIL_SECRET = "sgbzgtqhmgmbxxxxxx"

VITE_GOOGLE_CLIENT = "289153080841-7v6rvdgkfa8r66ju27dar2utd5deh09a.apps.googleusercontent.com"

Client-side console log:
![Screenshot from 2023-09-22 14-55-41](https://github.com/ansonbenny/Music-Streamer/assets/130034273/2af79c42-46db-4627-b9bd-a845e2edbfc2)

Server-side console log:
![Screenshot from 2023-09-22 14-55-38](https://github.com/ansonbenny/Music-Streamer/assets/130034273/d99ef720-1123-44f6-bcb6-a7512bc11c8f)


let know what i'm doing wrong

**Comment by ansonbenny** [comment]
that's not code issues, when you are not logged (or when jwt token expired) that will show

**Comment by ansonbenny** [comment]
you must fill SITE_URL = [when local run http://localhost:5173/ or your site domain for work cors & mail links]

**Comment by arun-nextbrain** [comment]
> that's not code issues, when you are not logged (or when jwt token expired) that will show

Where I can get the JWT token?

**Comment by ansonbenny** [comment]
> > that's not code issues, when you are not logged (or when jwt token expired) that will show
> 
> Where I can get the JWT token?

that will auto generate when user login and save token into cookie,
to work cookie you must fill SITE_URL in .env

**Comment by ansonbenny** [comment]
VITE_GOOGLE_CLIENT in .env.local in react folder
other env property and values in .env in server folder

**Comment by arun-nextbrain** [comment]
> > > that's not code issues, when you are not logged (or when jwt token expired) that will show
> > 
> > 
> > Where I can get the JWT token?
> 
> that will auto generate when user login and save token into cookie, to work cookie you must fill SITE_URL in .env

Now I'm fill the SITE_URL and checking but the same error will shown

can you please guide me to setup the project on my local system 

Also when I click the signup, login button and play button the screen was blank nothing will happen why?

**Comment by ansonbenny** [comment]
> > > > that's not code issues, when you are not logged (or when jwt token expired) that will show
> > > 
> > > 
> > > Where I can get the JWT token?
> > 
> > 
> > that will auto generate when user login and save token into cookie, to work cookie you must fill SITE_URL in .env
> 
> Now I'm fill the SITE_URL and checking but the same error will shown
> 
> can you please guide me to setup the project on my local system
> 
> Also when I click the signup, login button and play button the screen was blank nothing will happen why?

share screenshot

**Comment by ansonbenny** [comment]
[.env.txt](https://github.com/ansonbenny/Music-Streamer/files/12699620/default.env.txt)

this env file for server folder

**Comment by ansonbenny** [comment]
[.env.local.txt](https://github.com/ansonbenny/Music-Streamer/files/12699627/default.env.local.txt)

this one for client folder

**Comment by arun-nextbrain** [comment]
@ansonbenny Thanks bro now it's working
thanks a lot for your help
